---
  - name: Install unattended updates package
    tags: [autoupdates]
    become: true
    package:
      name: unattended-upgrades
      state: present

  - name: Copy unattended-upgrades configuration files in place.
    tags: [autoupdates]
    become: true
    template:
      src: "{{ item }}.j2"
      dest: "/etc/apt/apt.conf.d/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - 10periodic
      - 50unattended-upgrades
