
#   ____                     ____
#  / _(_)______ _    _____ _/ / /
# / _/ / __/ -_) |/|/ / _ `/ / / 
#/_//_/_/  \__/|__,__/\_,_/_/_/  
#                                
# # # # # # # # # # # # # # # # # # # # # # # #

# Allowed ports
firewall_allowed_tcp_ports:
  - "{{ ssh_port }}"
  - "25"
  - "80"
  - "8080"
  - "443"
  - "465"
  - "587"
  - "993"

# Service state, iptables flush
firewall_state: started
firewall_enabled_at_boot: true
firewall_flush_rules_and_chains: false


# Other iptable rules
firewall_allowed_udp_ports: []
firewall_forwarded_tcp_ports: []
firewall_forwarded_udp_ports: []
firewall_additional_rules: []
firewall_enable_ipv6: true
firewall_ip6_additional_rules: []
firewall_log_dropped_packets: true

# Set true to disable other firewall managements
firewall_disable_firewalld: false
firewall_disable_ufw: false
