---

  - name: Ensure old versions of Docker are not installed.
    become: true 
    tags: ["docker"]
    package:
      name:
        - docker
        - docker.io
        - docker-engine
        - docker-compose
        - docker-doc
        - podman-docker
        - containerd
        - runc
      state: absent

  - name: Ensure additional dependencies are installed (on Ubuntu >= 20.04).
    become: true 
    tags: ["docker"]
    apt:
      name: 
        - ca-certificates 
        - curl
        - gnupg
      state: present
  
  - name: Add Docker apt key.
    become: true 
    tags: ["docker"]
    ansible.builtin.get_url:
      url: "{{ docker_apt_gpg_key }}"
      dest: /etc/apt/trusted.gpg.d/docker.asc
      mode: '0644'
      force: false
      checksum: "{{ docker_apt_gpg_key_checksum | default(omit) }}"
    register: add_repository_key
    ignore_errors: "{{ docker_apt_ignore_key_error }}"
    when: docker_add_repo | bool
  
  - name: Ensure curl is present (on older systems without SNI).
    become: true 
    tags: ["docker"]
    package: name=curl state=present
    when: add_repository_key is failed and docker_add_repo | bool
  
  - name: Add Docker apt key (alternative for older systems without SNI).
    become: true 
    tags: ["docker"]
    shell: >
      curl -sSL {{ docker_apt_gpg_key }} | apt-key add -
    when: add_repository_key is failed and docker_add_repo | bool
  
  - name: Add Docker repository.
    become: true 
    tags: ["docker"]
    apt_repository:
      repo: "{{ docker_apt_repository }}"
      state: present
      filename: "{{ docker_apt_filename }}"
      update_cache: true
    when: docker_add_repo | bool
